Source/Kantoratus/Kantoratus.WebApp/Controllers/BaseController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class BaseController : Controller
    {
        protected readonly PersistenceService Persistence;

        public BaseController(Context context)
        {
            Persistence = new PersistenceService(context);
        }

        protected override void Dispose(bool disposing)
        {
            Persistence.Dispose();
            base.Dispose(disposing);
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/ComposersController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class ComposersController : BaseController
    {
        public ComposersController(Context context) : base(context)
        {
        }
        public IActionResult Index()
        {
            return View(Persistence.GetComposers(null));
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/EventsController.cs
using System.Collections.Generic;
using System.Linq;
using Kantoratus.Domain;
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class EventsController : BaseController
    {
        public EventsController(Context context) : base(context)
        {
        }
        public IActionResult Index(int? year = null)
        {
            var years = Persistence.GetYears();

            if (!years.Any())
            {
                return View(new EventList { Years = new List<int>(), Events = new List<Event>() });
            }

            if (year == null)
            {
                year = years.Min();
            }

            return View(new EventList
            {
                ActiveYear = year.Value,
                Years = years.ToList(),
                Events = Persistence.GetEvents(null, year)
            });
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/HomeController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(Context context) : base(context)
        {
        }

        public IActionResult Index()
        {
            return View(Persistence.GetFacts());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View();
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/MembersController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class MembersController : BaseController
    {
        public MembersController(Context context) : base(context)
        {
        }
        public IActionResult Index()
        {
            return View(Persistence.GetMembers(null));
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/PiecesController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class PiecesController : BaseController
    {
        public PiecesController(Context context) : base(context)
        {
        }

        public IActionResult Index()
        {
            return View(Persistence.GetPieces(null));
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/PlaylistsController.cs
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class PlaylistsController : BaseController
    {
        public PlaylistsController(Context context) : base(context)
        {
        }

        public IActionResult Index()
        {
            return View(Persistence.GetPlayLists(null));
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Controllers/SearchController.cs
using Kantoratus.Domain;
using Kantoratus.Persistence;
using Microsoft.AspNetCore.Mvc;

namespace Kantoratus.WebApp.Controllers
{
    public class SearchController : BaseController
    {
        public SearchController(Context context) : base(context)
        {
        }

        public IActionResult Index(string query)
        {
            return View(string.IsNullOrEmpty(query)
                ? new SearchResults { Query = query }
                : new SearchResults
                {
                    Query = query,
                    PlayLists = Persistence.GetPlayLists(query),
                    Pieces = Persistence.GetPieces(query),
                    Composers = Persistence.GetComposers(query),
                    Members = Persistence.GetMembers(query),
                    Events = Persistence.GetEvents(query, null)
                });
        }
    }
}

Source/Kantoratus/Kantoratus.WebApp/Views/Composers/ComposersPartial.cshtml
@model IEnumerable<Kantoratus.Domain.Initial>

<section class="songs-details-section">
    <div class="card-columns">
        @foreach (var initial in Model)
        {
            <div class="card border-0 mx-auto">
                <div class="card-body">
                    <div class="song-details-box">
                        <h3>@initial.Letter</h3>
                        <ul>
                            @foreach (var composer in initial.Categories)
                            {
                                <li><strong>@composer.Name</strong></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Source/Kantoratus/Kantoratus.WebApp/Views/Composers/Index.cshtml
@model IEnumerable<Kantoratus.Domain.Initial>

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h2>Korál- és genfizsoltár-feldolgozások szerzői</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <p>
                    A kelenföldi vesperák kezdő- és záróéneke valamint a himnusz helyén többnyire az Evangélikus énekeskönyv és a Gyülekezeti liturgikus könyv koráljai kapnak helyet – ezzel is segítve a gyülekezet aktív bekapcsolódását. A zsoltározás recitált formája mellett kezdettől jelen vannak a genfi zsoltárok. Az általában alternatim módon énekelt korál- és genfizsoltár-feldolgozások szerzőit jegyzékszerűen közöljük.
                </p>
            </div>
        </div>
    </div>
</section>

<partial name="ComposersPartial" />

Source/Kantoratus/Kantoratus.WebApp/Views/Contacts/Index.cshtml
<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="contact-warp">
                    <div class="section-title mb-0">
                        <h2>Elérhetőség</h2>
                    </div>
                    <p>
                        A Fővárosi Protestáns Kántorátus együttese a tanév minden vasárnapján 18 órakor többszólamú tételekkel díszített vesperát énekel a kelenföldi evangélikus templomban (XI. Bocskai út 10.). Minden érdeklődőt szeretettel várunk!
                    </p>
                    <ul>
                        <li>
                            <a href="https://kelenfold.lutheran.hu/alkalmaink/istentiszteletek/ " target="_blank">
                                <i class="fas fa-church"></i>
                                Kelenföldi Evangélikus Gyülekezet
                            </a>
                        </li>
                    </ul>
                    <p>
                        Az együttes folyamatosan várja az egyházi szolgálat iránt elkötelezett, jó hangú, biztos kottaolvasó énekesek jelentkezését vegyeskari felállás minden szólamába.
                        A kántorátus vezetője Pap Kinga Marjatta.
                    </p>
                    <ul>
                        <li>
                            <a href="https://goo.gl/maps/jzJLsYypFnTfvR8A6">
                                <script TYPE="text/javascript">
                                    emailE = 'gmail.com';
                                    emailE = ('kuninga' + '@@' + emailE);
                                    document.write('<A href="mailto:' +
                                        emailE +
                                        '"><i class="fas fa-envelope"></i> ' +
                                        emailE +
                                        '</a>');
                                </script>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-warp">
                    <div id="fb-root"></div>
                    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/hu_HU/sdk.js#xfbml=1&version=v9.0" nonce="4urMjK19"></script>
                    <div class="fb-page"
                         data-href="https://www.facebook.com/F%C5%91v%C3%A1rosi-Protest%C3%A1ns-K%C3%A1ntor%C3%A1tus-2489253114423466"
                         data-tabs="events"
                         data-width=""
                         data-height=""
                         data-small-header="false"
                         data-adapt-container-width="true"
                         data-hide-cover="false"
                         data-show-facepile="false">
                        <blockquote cite="https://www.facebook.com/F%C5%91v%C3%A1rosi-Protest%C3%A1ns-K%C3%A1ntor%C3%A1tus-2489253114423466" class="fb-xfbml-parse-ignore">
                            <a href="https://www.facebook.com/F%C5%91v%C3%A1rosi-Protest%C3%A1ns-K%C3%A1ntor%C3%A1tus-2489253114423466">Fővárosi Protestáns Kántorátus</a>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Source/Kantoratus/Kantoratus.WebApp/Views/Events/EventsPartial.cshtml
@model List<Kantoratus.Domain.Event>

<script src="~/js/events.js" asp-append-version="true"></script>


@for (var i = 0; i < Model.Count; ++i)
{
    @if (Model[i].IsArticle)
    {
        <div class="player-box blog-item">
            <div class="wave-player-info">
                <div class="blog-date">@Model[i].Date</div>
                <div class="blog-meta">@Model[i].Location</div>
                <h2 class="black">@Model[i].Title</h2>
                <div class="w3-content w3-display-container">
                    @foreach (var image in Model[i].Images)
                    {
                        <a href="@image"><img class="slideImage @i" src="@image"></a>
                    }

                    @if (Model[i].Images.Count() > 1)
                    {
                        <button class="w3-button w3-display-left" onclick="plusDivs(-1, @i)">&#10094;</button>
                        <button class="w3-button w3-display-right" onclick="plusDivs(+1, @i)">&#10095;</button>
                    }

                    <script>
                                addSlideShow(@i);
                    </script>
                </div>
                <div class="black">@Html.Raw(Model[i].Description)</div>
            </div>
        </div>
    }
    else
    {
        <div class="blog-item">
            <div class="blog-date">@Model[i].Date</div>
            <div class="blog-meta">@Model[i].Location</div>
            <h3>@Model[i].Title</h3>
            <div class="w3-content w3-display-container">
                @foreach (var image in Model[i].Images)
                {
                    <a href="@image"><img class="slideImage @i" src="@image"></a>
                }

                @if (Model[i].Images.Count() > 1)
                {
                    <button class="w3-button w3-display-left" onclick="plusDivs(-1, @i)">&#10094;</button>
                    <button class="w3-button w3-display-right" onclick="plusDivs(+1, @i)">&#10095;</button>
                }

                <script>
                                addSlideShow(@i);
                </script>
            </div>
            @Html.Raw(Model[i].Description)
        </div>
    }
}

Source/Kantoratus/Kantoratus.WebApp/Views/Events/Index.cshtml
@model Kantoratus.Domain.EventList

<script src="~/js/events.js" asp-append-version="true"></script>

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h2>Kiemelt események</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <p>
                    A hetenkénti vesperaszolgálat mellett kiemelt események is kísérték a kántorátus útját: önálló hangversenyek, ünnepi szolgálatok, szakmai bemutatók és tematikus sorozatok mellett zenésztársakkal, más együttesekkel közös kisebb-nagyobb vállalkozásokban is részt vettünk ökumenikus, nemzetközi és hazai körben. Az évek során jelen lehettünk az emberi élet fordulópontjain: a kántorátus egyaránt szolgált keresztelőn, esküvőn, örömteli születésnapi alkalmakon és temetési búcsúztatáson.
                </p>
            </div>
        </div>
    </div>
</section>

<section class="blog-section spad">
    <div class="container">
        <partial name="PaginationPartial" />
        <partial name="EventsPartial" model="Model.Events"/>
        <partial name="PaginationPartial" />
    </div>
</section>

Source/Kantoratus/Kantoratus.WebApp/Views/Events/PaginationPartial.cshtml
@model Kantoratus.Domain.EventList

<div class="site-pagination">
    @foreach (var year in Model.Years.Where(y => y < Model.ActiveYear))
    {
        <a asp-action="Index" asp-controller="Events" asp-route-year="@year">@year</a>
    }
    <a href="#" class="active">@Model.ActiveYear</a>
    @foreach (var year in Model.Years.Where(y => y > Model.ActiveYear))
    {
        <a asp-action="Index" asp-controller="Events" asp-route-year="@year">@year</a>
    }
</div>

Source/Kantoratus/Kantoratus.WebApp/Views/Home/Index.cshtml
@model Kantoratus.Domain.Facts

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h2>@Model.Age éves a Fővárosi Protestáns Kántorátus</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <p>
                    Az alapításkor három együttes alkotta a Fővárosi Kántorátust: a Szent István Bazilikában szolgáló és a Budapesti Énekes Iskolához köthető katolikus, valamint a kelenföldi protestáns „ágazat”. Azóta több helyen alakultak rokon célokat ápoló együttesek: a reformátusok Budafokon 2004 óta, a Kálvin téren 2006 óta havonta énekelnek vesperát. A Gödöllői Premontrei Kántorátus 2009-től, a Belvárosi Kántorátus 2018-tól végez rendszeres szolgálatot. Ferencvárosban 2011-ben alakult evangélikus kántorátus, több vidéki városban (például Orosházán és Szombathelyen) pedig a nagyobb ünnepekhez kötve tartanak zsoltározó alkalmakat.
                </p>
                <p>
                    A kelenföldi együttes specifikuma, hogy az utánpótlást biztosító intézményrendszer felépítése nélkül sikerült mindeddig fenntartani a heti rendszerességű, többszólamú tételekkel gazdagított liturgikus szolgálatot.
                </p>
            </div>
        </div>
    </div>
</section>

<section class="how-section spad set-bg">
    <div class="container text-white">
        <div class="section-title">
            <h2>Mi minden fért bele ebbe a @Model.Age évbe?</h2>
            <h3>Röviden szólva</h3>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="how-item">
                    <div class="hi-icon">
                        <i class="fas fa-users fa-5x"></i>
                    </div>
                    <h4>@Model.MemberCount ember</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="how-item">
                    <div class="hi-icon">
                        <i class="fas fa-book-open fa-5x"></i>
                    </div>
                    <h4>@Model.PieceCount önálló mű</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="how-item">
                </div>
            </div>
            <div class="col-md-4">
                <div class="how-item">
                    <div class="hi-icon">
                        <i class="fas fa-pen-fancy fa-5x"></i>
                    </div>
                    <h4>Korál- és genfizsoltár-feldolgozások 90 szerzőtől</h4>
                </div>
            </div>
            <div class="col-md-4">
                <div class="how-item">
                    <div class="hi-icon">
                        <i class="fas fa-church fa-5x"></i>
                    </div>
                    <h4>@Model.VespersCount vespera (abból mintegy 800 Bence Gábor alapítókarnagy vezetésével)</h4>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>
                    Az együttes szolgálatának fókusza az élő zenei imádság, mely hangzóanyagként csak töredékes lenyomatként adható vissza. Lejátszási listáinkon visszatekintő válogatást és friss felvételeket egyaránt kínálunk.
                </p>
                <p>
                    Az önállóan elhangzott művek jegyzéke nem csak a repertoárválasztás súlypontjaiba és egyre bővülő forrásaiba nyújt betekintést, de a szólam-összeállításból az együttes életének változatos időszakai is kirajzolódnak. A gazdag motettaanyag más felekezetű kollegák számára is gondolatébresztő lehet.
                </p>
                <p>
                    A rendszerint alternatim módon énekelt korál- és genfizsoltár-feldolgozások szerzőit jegyzékszerűen közöljük. A kántorátustagok generációinak névsora minden olyan énekest tartalmaz, aki egynél több alkalommal részt vett a szolgálatban.
                </p>
                <p>
                    Kiemelt események is kísérték a kántorátus útját: önálló hangversenyek, ünnepi szolgálatok, szakmai bemutatók és tematikus sorozatok mellett zenésztársakkal, más együttesekkel közös kisebb-nagyobb vállalkozásokban is részt vettünk ökumenikus, nemzetközi és hazai körben.
                </p>
                <p>
                    A közölt anyag a teljesség igényére való törekvéssel, a rendelkezésre álló források alapján készült. A 25. évfordulóra könyv formában is megjelent ünnepi összeállítás készítésében munkatársaim voltak Isó M. Emese, László Dávid és Nagy Szabolcs. Köszönet a kelenföldi énekkari napló gondos vezetéséért az adott időszakban Ittzés Andrásnak és Gadóné Kézdy Editnek, a kántorátus motettaanyagának rendszerezéséért az adott időszakban Ecsedi Klárának, továbbá a Magyar Egyházzenei Társaság és a Magyar Rádió munkatársainak, Aradi György fasori evangélikus lelkésznek, valamint Marton Tamás egykori Szélrózsa-szervezőnek, akik aktívan hozzájárultak a gyűjtőmunkához.
                </p>
                <p>
                    Végül néhány személyes mondat: alapító énekesként az évek során rengeteget tanulhattam elsősorban stílus- és repertoárismeret terén. Az együttes vezetőjének lenni azonban mást is jelent: egész héten foglalkoztat a vasárnap igerendje és az arra való zenei reflektálás. A megvalósítás sokféle gondja közt ez az igazi ajándék ebben a szolgálatban.
                </p>
                <p>
                    <i>Egy dolgot kérek az Úrtól, azért esedezem: hogy az Úr házában lakhassam egész életemben.</i> (Zsolt 27,4a)
                </p>
                <p>
                    Pap Kinga Marjatta
                </p>
            </div>
            <div class="col-lg-6">
                <img class="slides w3-animate-fading" src="~/img/slideshow/0C7V1543.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/2002_09_kantoratus_kep.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/23755800_1477830505666744_1522660936402166060_n.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/dsc_0070.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/EvÉlet 2002_11_03.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/IMG_20170924_191520.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/img_4516.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/martonnap2019111068.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/martonnap2019111080.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/martonnap2019111082.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Unnepi_vespera295.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Unnepi_vespera299.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Zalaegerszeg 2017.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Zalaegerszeg 2017_2.jpg">

                <img class="slides w3-animate-fading" src="~/img/slideshow/553543069_33248114894787485_3658064857666748579_n.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/608430315_1200319632075342_5053859071083874759_n.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/IMG_20240225_185519.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Vesperasorozat 2025.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Vesperasorozat 2025_0.png">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Vesperasorozat 2025_1.jpg">
                <img class="slides w3-animate-fading" src="~/img/slideshow/Vesperasorozat 2025_2.jpg">
            </div>
        </div>
    </div>
</section>

<script src="~/js/home.js" asp-append-version="true"></script>

Source/Kantoratus/Kantoratus.WebApp/Views/Members/Index.cshtml
@model IEnumerable<Kantoratus.Domain.Initial>

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h2>A Fővárosi Protestáns Kántorátus tagjai</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <p>
                    Az együttesbe az évtizedek során számos irányból érkeztek aktív szolgálattevők. A gyülekezethez kötődő gyakorlott kórusénekesek mellett sokan a Deák Téri Evangélikus Gimnázium valamint a Magyarországi Evangélikus Egyház Kántorképző Intézetének (volt) diákjai. A Liszt Ferenc Zeneművészeti Egyetem egyházzene tanszakának protestáns hallgatói és az Evangélikus Hittudományi Egyetem kántorszakos hallgatói számára gyakorlati helyként is működik az együttes – néhányan közülük a kötelező időszak lejártával is az együttes szolgálói maradtak. A kántorátustagok generációinak névsora minden olyan énekest tartalmaz, aki egynél több alkalommal részt vett a szolgálatban.
                </p>
            </div>
        </div>
    </div>
</section>

<partial name="MembersPartial" />

<section class="intro-section spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-title">
                    <h2>Az együttes örökös tagjai</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card border-0 mx-auto">
                    <div class="card-body">
                        <div class="song-details-box">
                            <ul>
                                <li><strong>Béres Márk</strong></li>
                                <li><strong>Ecsedi Klára</strong></li>
                                <li><strong>Mády Katalin</strong></li>
                                <li><strong>Pap Kinga Marjatta</strong></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Source/Kantoratus/Kantoratus.WebApp/Views/Members/MembersPartial.cshtml
@model IEnumerable<Kantoratus.Domain.Initial>

<section class="songs-details-section">
    <div class="card-columns">
        @foreach (var initial in Model)
        {
            <div class="card border-0 mx-auto">
                <div class="card-body">
                    <div class="song-details-box">
                        <h3>@initial.Letter</h3>
                        <ul>
                            @foreach (var member in initial.Categories)
                            {
                                <li><strong>@member.Name</strong></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

Source/Kantoratus/Kantoratus.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="A Fővárosi Protestáns Kántorátus 1996 óta végez heti rendszerességű liturgikus szolgálatot a kelenföldi evangélikus templomban (Bp. XI., Bocskai út 10.). A vasárnap este 6 órakor kezdődő vesperás istentiszteleten a rövid igehirdetés mellett a kántorátus és a gyülekezet közös és váltakozó énekével gregorián és genfi zsoltárok szólalnak meg, a kántorátus alternatim korálfeldolgozásokat és hetente változó motettákat énekel. A kantoratus.hu a folyamatosan szolgáló együttes első 25 évének szakmai anyagát és eseményeit foglalja össze.">
    <meta name="keywords"
          content="kántorátus, jubileum, vespera, liturgia, GyLK, evangélikus, protestáns, Kelenföld, motetta, korál, genfi zsoltár, zsoltározás, Dobszay László, Bence Gábor, Pap Kinga Marjatta">

    <title>Fővárosi Protestáns Kántorátus</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/css/slicknav.min.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="~/css/style.css" />

</head>
<body>

    <div id="preloder">
        <div class="loader"></div>
    </div>

    <div class="content">
        <div class="content-inside">
            <header class="header-section clearfix">
                <a asp-action="Index" asp-controller="Home" class="site-logo">
                    <h1>Fővárosi Protestáns Kántorátus</h1>
                </a>

                <ul class="main-menu">
                    <li>
                        <a asp-action="Index" asp-controller="Playlists">Hangzóanyag</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Pieces">Önálló művek</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Composers">Feldolgozások szerzői</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Members">Tagok</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Events">Kiemelt események</a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Contacts">Elérhetőség</a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/F%C5%91v%C3%A1rosi-Protest%C3%A1ns-K%C3%A1ntor%C3%A1tus-2489253114423466" target="_blank">
                            <i class="fab fa-facebook-square"></i>
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Search"><i class="fas fa-search"></i></a>
                    </li>
                </ul>
            </header>
            @RenderBody()
        </div>
    </div>

    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-7 order-lg-1"></div>
                <div class="col-xl-6 col-lg-7 order-lg-2 copyright">
                    &copy;
                    <script>document.write(new Date().getFullYear());</script> <a href="https://www.linkedin.com/in/bzfelix/">Bárándi Zoltán Félix</a>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/mixitup.min.js"></script>
    <script src="~/js/jquery.slicknav.min.js"></script>
    <script src="~/js/main.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>